name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to deploy'
        required: false
        default: dist
        type: string
    # secrets:
    #   some-secret:
    #     required: false
    outputs:
      result:
        description: 'Name of the artifact to deploy'
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Output information
        run: echo "Deploying..."
      - name: Output result
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
